---
- hosts: webserver
  become: true
  become_user: root
  tasks:
    - name: Update system using Yum
      yum: 
        name: '*'
        state: latest
    - name: Install Docker
      yum: 
        name: docker
        state: present
        update_cache: true
    - name: Install Nginx
      yum: 
        name: nginx
        state: present
        update_cache: true